# Generated by Django 5.1.7 on 2025-04-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
