# Generated by Django 5.1.7 on 2025-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productQtd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('quantidade_estoque', models.IntegerField()),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/')),
                ('imagem4', models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/')),
            ],
        ),
    ]
