# Generated by Django 5.1.7 on 2025-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagem/produtos/'),
        ),
    ]
